In [1]:
import pandas as pd
import numpy as np
import requests
from functools import reduce
import matplotlib.pyplot as plt
import pickle
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 150)
import sys
sys.path.append("../../Functions and Dictionaries") # Adds higher directory to python modules path
import geodict
GNRC = geodict.GNRC
KY = geodict.KY
censusplaces = geodict.censusplaces
tofullcensus = geodict.tofullcensus
geotogeoid = geodict.geotogeoid
shorttnplaces = geodict.shorttnplaces
shortkyplaces = geodict.shortkyplaces
GNRC = geodict.GNRC
KY = geodict.KY
censusplaces = geodict.censusplaces
import tbrstuff
communitycollegescounties = tbrstuff.communitycollegescounties
tcatcampuscounties = tbrstuff.tcatcampuscounties
import sqlite3 as sq

In [10]:
data = pd.read_csv('../Data/Subas.csv', dtype = str)

In [11]:
data = data[['Institution Type', 'Institution', 'Campus', 'County', 'FIPS', 'Institution Address', 'Latitude', 'Longitude']]
data = data.drop_duplicates().reset_index()

In [12]:
data.head()

,index,Institution Type,Institution,Campus,County,FIPS,Institution Address,Latitude,Longitude
0,0,TCAT,Athens,Main Campus,"McMinn County, Tennessee",47107,"1635 Technology Way, Athens, TN 37303",35.44283231,-84.63048532
1,32,TCAT,Athens,McMinn Higher Education Center Extension Campus,NaN,NaN,NaN,NaN,NaN
2,33,TCAT,Chattanooga,ChSCC - West Campus,"Hamilton County, Tennessee",47065,"4501 Amnicola Hwy #100, Chattanooga, TN 37406",35.10104203,-85.23556756
3,45,TCAT,Chattanooga,Construction Career Center,NaN,NaN,NaN,NaN,NaN
4,46,TCAT,Chattanooga,Kansita Building,"Hamilton County, Tennessee",47065,"4501 Amnicola Hwy #100, Chattanooga, TN 37406",35.10104203,-85.23556756

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147 entries, 0 to 146
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   index                147 non-null    int64
 1   Institution Type     147 non-null    object
 2   Institution          147 non-null    object
 3   Campus               147 non-null    object
 4   County               134 non-null    object
 5   FIPS                 133 non-null    object
 6   Institution Address  121 non-null    object
 7   Latitude             121 non-null    object
 8   Longitude            121 non-null    object
dtypes: int64(1), object(8)
memory usage: 10.5+ KB

In [21]:
data.to_csv('locations.csv', index = False)

In [18]:
nulls = data[data['Institution Address'].isna()]

In [20]:
nulls

,index,Institution Type,Institution,Campus,County,FIPS,Institution Address,Latitude,Longitude
1,32,TCAT,Athens,McMinn Higher Education Center Extension Campus,NaN,NaN,NaN,NaN,NaN
3,45,TCAT,Chattanooga,Construction Career Center,NaN,NaN,NaN,NaN,NaN
5,49,TCAT,Chattanooga,Kansita Building ...,NaN,NaN,NaN,NaN,NaN
8,298,TCAT,Chattanooga,Rhea County Industrial Park,"Rhea County, Tennessee",47143,NaN,NaN,NaN
9,304,TCAT,Chattanooga,Suburban Manufacturing,"Hamilton County, Tennessee",47065,NaN,NaN,NaN
15,577,TCAT,Crump,Adamsville High School,NaN,NaN,NaN,NaN,NaN
19,594,TCAT,Crump,Decatur County Riverside High School,NaN,NaN,NaN,NaN,NaN
25,658,TCAT,Crump,Wayne County Technology Center,"Wayne County, Tennessee",47181,NaN,NaN,NaN
28,712,TCAT,Dickson,Franklin Extension,"Williamson County, Tennessee",47187,NaN,NaN,NaN
32,846,TCAT,Elizabethton,Cloudland High School,NaN,NaN,NaN,NaN,NaN
37,909,TCAT,Elizabethton,Mountain City Extension Campus,NaN,NaN,NaN,NaN,NaN
41,966,TCAT,Hartsville,Hendersonville High School,"Sumner County, Tennessee",47165,NaN,NaN,NaN
44,1000,TCAT,Hartsville,Smith County High School,"Smith County, Tennessee",47159,NaN,NaN,NaN
50,1042,TCAT,Hohenwald,Lawrence County Instructional Service Center,"Lawrence County, Tennessee",47099,NaN,NaN,NaN
55,1120,TCAT,Hohenwald,Summertown ISC,NaN,NaN,NaN,NaN,NaN
74,1462,TCAT,Knoxville,Pellissippi State Community College -Strawberr...,"Knox County, Tennessee",47093,NaN,NaN,NaN
75,1469,TCAT,Knoxville,Ruth and Steve West Extension Campus,NaN,NaN,NaN,NaN,NaN
76,1470,TCAT,Livingston,Clay County High School,"Clay County, Tennessee",47027,NaN,NaN,NaN
83,1581,TCAT,McKenzie,Weakley County Center for Adults,"Weakley County, Tennessee",47183,NaN,NaN,NaN
98,1841,TCAT,Morristown,Newport Instructional Service Center,"Cocke County, Tennessee",47029,NaN,NaN,NaN
115,2262,TCAT,Newbern,TCAT Newbern - Transportation Campus,"Dyer County, Tennessee",47045,NaN,NaN,NaN
125,2515,TCAT,Paris,Weakley County Center for Adults,"Weakley County, Tennessee",47183,NaN,NaN,NaN
135,2882,TCAT,Shelbyville,Adult Education Center,"Bedford County, Tennessee",47003,NaN,NaN,NaN
136,2884,TCAT,Shelbyville,Don Sundquist Center of Advanced Technologies,"Bedford County, Tennessee",47003,NaN,NaN,NaN
137,2885,TCAT,Shelbyville,Franklin County Business Center,"Franklin County, Tennessee",47051,NaN,NaN,NaN
145,3281,TCAT,Whiteville,Brownsville Extension Campus,"Haywood County, Tennessee",47075,NaN,NaN,NaN