In [1247]:
import pandas as pd
import numpy as np
import requests
from functools import reduce
import matplotlib.pyplot as plt
import pickle
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 150)
import sys
sys.path.append("../../Functions and Dictionaries") # Adds higher directory to python modules path
import CIPCodes
fam = CIPCodes.programfam
fam_inv = {v: k for k, v in fam.items()}
cat = CIPCodes.programcat
cat_inv = {v: k for k, v in cat.items()}
prog = CIPCodes.program
prog_inv = {v: k for k, v in prog.items()}
import geodict
tncountyfips = geodict.alltncountyfips

In [1248]:
oldest = pd.read_csv('../Data Downloads/TBR_TCAT_20192020_20212022.csv')
oldest.head(2)

   Total Awards   Award Type     Year Institution                                       Campus  Six Digit CIP
0             2  Certificate  2019-20   Knoxville  Anderson County Career and Technical Center         480508
1             7      Diploma  2019-20   Knoxville  Anderson County Career and Technical Center         480508

In [1249]:
#renamed in 2023-2024
oldest.loc[(oldest["Institution"] == "Whiteville")&(oldest["Campus"] == "Main Campus"), "Campus"] = "Whiteville"
oldest['Institution'] = oldest['Institution'].replace({'Crossville': 'Upper Cumberland',
                                                       'Newbern': 'Northwest', 
                                                       'Covington': 'Northwest', 
                                                       'Ripley': 'Northwest',
                                                       'Whiteville': 'Jackson', 
                                                       'Paris': 'Henry/Carroll'
                                                      })
oldest['Campus'] = oldest['Campus'].replace({'TCAT Newbern - Union City Campus': 'Union City Campus', 
                                             'TCAT Newbern - Transportation Campus': 'Transportation Campus', 
                                             'TCAT Newbern - Bells Campus': 'Bells Campus', 
                                             'Brownsville Extension Campus': 'Brownsville/Haywood Extension Campus', 
                                             'Maury County Instructional Service Center': 'Maury Regional Medical Center ISC', 
                                             'Spring Hill High School Instructional Service Cent': 'Spring Hill High School Instructional Service Center', 
                                             'Pellissippi State Community College -Strawberry Pl': 'Pellissippi State Community College -Strawberry Plains', 
                                           'Humboldt Higher Education Instructional Service Ce': 'Humboldt Higher Education Instructional Service Center', 
                                             'Greene County Instructional Service Center': 'Greeneville Instructional Service Center', 
                                             'Lawrenceburg Instructional Service': 'Lawrenceburg Instructional Service Center', 
                                             'Franklin County Business Center': 'Franklin County Extension Campus'
                                            })

In [1250]:
test = oldest.loc[oldest['Institution'] == 'Hohenwald']
test['Campus'].unique()

array(['Lawrence County Instructional Service Center', 'Main Campus',
       'Columbia Central High School Instructional Service',
       'Maury Regional Medical Center ISC',
       'Spring Hill High School Instructional Service Center',
       'Perry County Instructional Service Center',
       'Wayne County Instructional Service Center',
       'Wayne Medical Instructional Service Center'], dtype=object)

In [1251]:
older = pd.read_csv('../Data Downloads/TBR_TCAT_20222023.csv')
older.head(2)

   Total Awards Institution   Award Type     Year       Campus  Six Digit CIP
0            12      Athens  Certificate  2022-23  Main Campus         480508
1             1      Athens  Certificate  2022-23  Main Campus         480501

In [1252]:
older.loc[(older["Institution"] == "Whiteville")&(older["Campus"] == "Main Campus"), "Campus"] = "Whiteville"
#renamed in 2023-2024
older['Institution'] = older['Institution'].replace({'Crossville': 'Upper Cumberland',
                                                     'Newbern': 'Northwest', 
                                                     'Covington': 'Northwest', 
                                                     'Ripley': 'Northwest', 
                                                     'Whiteville': 'Jackson', 
                                                       'Paris': 'Henry/Carroll'
                                                      })
older['Campus'] = older['Campus'].replace({'TCAT Newbern - Union City Campus': 'Union City Campus', 
                                           'TCAT Newbern - Transportation Campus': 'Transportation Campus', 
                                           'TCAT Newbern - Bells Campus': 'Bells Campus', 
                                           'Brownsville Extension Campus': 'Brownsville/Haywood Extension Campus', 
                                           'Maury County Instructional Service Center': 'Maury Regional Medical Center ISC', 
                                           'Pellissippi State Community College -Strawberry Pl': 'Pellissippi State Community College -Strawberry Plains', 
                                           'Humboldt Higher Education Instructional Service Ce': 'Humboldt Higher Education Instructional Service Center', 
                                           'Greene County Instructional Service Center': 'Greeneville Instructional Service Center', 
                                           'Lawrenceburg Instructional Service': 'Lawrenceburg Instructional Service Center'
                                            })

In [1253]:
current = pd.read_csv('../Data Downloads/TBR_TCAT_20232024.csv')
current.head(2)

   Total Awards Institution   Award Type     Year       Campus  Six Digit CIP
0            10      Athens  Certificate  2023-24  Main Campus         480508
1             1      Athens  Certificate  2023-24  Main Campus         520402

In [1254]:
current['Campus'] = current['Campus'].replace({'Maury County Instructional Service Center': 'Maury Regional Medical Center ISC', 
                                               'Pellissippi State Community College -Strawberry Pl': 'Pellissippi State Community College -Strawberry Plains', 
                                           'Humboldt Higher Education Instructional Service Ce': 'Humboldt Higher Education Instructional Service Center', 
                                               'Greene County Instructional Service Center': 'Greeneville Instructional Service Center', 
                                               'TCAT Northwest - Covington': 'Covington Campus', 
                                               'TCAT Newbern - Bells Campus': 'Bells Campus', 
                                               'TCAT Northwest - Bells Campus': 'Bells Campus', 
                                               'TCAT Newbern - Union City Campus': 'Union City Campus', 
                                               'TCAT Northwest - Union City Campus': 'Union City Campus', 
                                               'TCAT Northwest - Ripley': 'Ripley Campus', 
                                               'Lawrenceburg Instructional Service': 'Lawrenceburg Instructional Service Center'
                                               
                                               
    
                                            })

In [1255]:
dfs = [oldest, older, current]
data = pd.concat(dfs)

In [1256]:
data.head()

   Total Awards   Award Type     Year Institution                                       Campus  Six Digit CIP
0             2  Certificate  2019-20   Knoxville  Anderson County Career and Technical Center         480508
1             7      Diploma  2019-20   Knoxville  Anderson County Career and Technical Center         480508
2             3      Diploma  2019-20   Knoxville  Anderson County Career and Technical Center         480501
3             6      Diploma  2019-20   Knoxville                        Oak Ridge High School         480508
4            10  Certificate  2020-21   Knoxville  Anderson County Career and Technical Center         480508

In [1257]:
data.tail()

     Total Awards Award Type     Year       Institution       Campus  Six Digit CIP
794             8    Diploma  2023-24  Upper Cumberland  Main Campus         470604
795             7    Diploma  2023-24  Upper Cumberland  Main Campus         470603
796             7    Diploma  2023-24  Upper Cumberland  Main Campus         480501
797             3    Diploma  2023-24  Upper Cumberland  Main Campus         470201
798            33    Diploma  2023-24  Upper Cumberland  Main Campus         513901

In [1258]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3936 entries, 0 to 798
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Total Awards   3936 non-null   int64
 1   Award Type     3936 non-null   object
 2   Year           3936 non-null   object
 3   Institution    3936 non-null   object
 4   Campus         3936 non-null   object
 5   Six Digit CIP  3936 non-null   int64
dtypes: int64(2), object(4)
memory usage: 215.2+ KB

In [1259]:
data['Six Digit CIP'] = data['Six Digit CIP'].astype(str)

In [1260]:
data['Six Digit CIP'] = data['Six Digit CIP'].str.zfill(6)

In [1261]:
data['Six Digit CIP'] = data['Six Digit CIP'].str.zfill(6).str.replace(r'^(\d{2})(\d+)$', r'\1.\2', regex=True)

In [1262]:
boop = data['Six Digit CIP'].str.split("", n = 7, expand = True)
data['Four Digit CIP'] = boop[1]+boop[2]+boop[3]+boop[4]+boop[5]
data['Two Digit CIP'] = boop[1]+boop[2]
boop.head(2)

  0  1  2  3  4  5  6  7
0    4  8  .  0  5  0  8
1    4  8  .  0  5  0  8

In [1263]:
data.head()

   Total Awards   Award Type     Year Institution                                       Campus Six Digit CIP Four Digit CIP Two Digit CIP
0             2  Certificate  2019-20   Knoxville  Anderson County Career and Technical Center       48.0508          48.05            48
1             7      Diploma  2019-20   Knoxville  Anderson County Career and Technical Center       48.0508          48.05            48
2             3      Diploma  2019-20   Knoxville  Anderson County Career and Technical Center       48.0501          48.05            48
3             6      Diploma  2019-20   Knoxville                        Oak Ridge High School       48.0508          48.05            48
4            10  Certificate  2020-21   Knoxville  Anderson County Career and Technical Center       48.0508          48.05            48

In [1264]:
data['Program Family'] = data['Two Digit CIP'].map(fam_inv)
data['Program Category'] = data['Four Digit CIP'].map(cat_inv)
data['Program'] = data['Six Digit CIP'].map(prog_inv)

In [1265]:
data.head()

,Total Awards,Award Type,Year,Institution,Campus,Six Digit CIP,Four Digit CIP,Two Digit CIP,Program Family,Program Category,Program
0,2,Certificate,2019-20,Knoxville,Anderson County Career and Technical Center,48.0508,48.05,48,Precision Production,Precision Metal Working,Welding Technology/Welder
1,7,Diploma,2019-20,Knoxville,Anderson County Career and Technical Center,48.0508,48.05,48,Precision Production,Precision Metal Working,Welding Technology/Welder
2,3,Diploma,2019-20,Knoxville,Anderson County Career and Technical Center,48.0501,48.05,48,Precision Production,Precision Metal Working,Machine Tool Technology/Machinist
3,6,Diploma,2019-20,Knoxville,Oak Ridge High School,48.0508,48.05,48,Precision Production,Precision Metal Working,Welding Technology/Welder
4,10,Certificate,2020-21,Knoxville,Anderson County Career and Technical Center,48.0508,48.05,48,Precision Production,Precision Metal Working,Welding Technology/Welder

In [1266]:
soc = pd.read_csv('../Data Downloads/CrosswalkCIPSOC.csv', dtype = str)
soc.drop(columns = 'Program', inplace = True)

In [1267]:
soc.head()

  Six Digit CIP 6 Digit SOC                                     Occupation
0       01.0000     19-1011                              Animal Scientists
1       01.0000     19-1012              Food Scientists and Technologists
2       01.0000     19-1013                      Soil and Plant Scientists
3       01.0000     19-4012                       Agricultural Technicians
4       01.0000     25-1041  Agricultural Sciences Teachers, Postsecondary

In [1268]:
data = data.merge(soc, on = 'Six Digit CIP')

In [1269]:
data.tail()

,Total Awards,Award Type,Year,Institution,Campus,Six Digit CIP,Four Digit CIP,Two Digit CIP,Program Family,Program Category,Program,6 Digit SOC,Occupation
13840,6,Certificate,2023-24,Elizabethton,Unaka High School,12.0506,12.05,12,"Culinary, Entertainment, and Personal Services",Culinary Arts and Related Services,Meat Cutting/Meat Cutter,51-3021,Butchers and Meat Cutters
13841,6,Certificate,2023-24,Elizabethton,Unaka High School,12.0506,12.05,12,"Culinary, Entertainment, and Personal Services",Culinary Arts and Related Services,Meat Cutting/Meat Cutter,51-3023,Slaughterers and Meat Packers
13842,5,Diploma,2023-24,Pulaski,Lawrence County Instructional Service Center,48.0510,48.05,48,Precision Production,Precision Metal Working,Computer Numerically Controlled (CNC) Machinis...,51-9161,Computer Numerically Controlled Tool Operators
13843,5,Diploma,2023-24,Pulaski,Lawrence County Instructional Service Center,48.0510,48.05,48,Precision Production,Precision Metal Working,Computer Numerically Controlled (CNC) Machinis...,51-9162,Computer Numerically Controlled Tool Programmers
13844,13,Certificate,2023-24,Shelbyville,Lincoln Central Academy,51.0000,51.00,51,Health Professions and Related Programs,"Health Services/Allied Health/Health Sciences,...","Health Services/Allied Health/Health Sciences,...",99-9999,NO MATCH

In [1270]:
locs = pd.read_csv('../Data Downloads/TCATLocations.csv')
locs.head()

,Institution,Campus,County,FIPS,Institution Address,Latitude,Longitude
0,Athens,Main Campus,"McMinn County, Tennessee",47107,"1635 Technology Way, Athens, TN 37303",35.442832,-84.630485
1,Athens,McMinn Higher Education Center Extension Campus,"McMinn County, Tennessee",47107,"2345 Denso Dr, Athens, TN 37303",35.471314,-84.647533
2,Chattanooga,ChSCC - West Campus,"Marion County, Tennessee",47115,"4501 Amnicola Hwy #100, Chattanooga, TN 37406",35.101042,-85.235568
3,Chattanooga,Construction Career Center,"Hamilton County, Tennessee",47065,"2225 Roanoke Ave, Chattanooga, TN 37406",35.061414,-85.259973
4,Chattanooga,Kansita Building,"Hamilton County, Tennessee",47065,"4501 Amnicola Hwy #100, Chattanooga, TN 37406",35.101042,-85.235568

In [1271]:
locs.tail()

,Institution,Campus,County,FIPS,Institution Address,Latitude,Longitude
141,Shelbyville,Main Campus,"Bedford County, Tennessee",47003,"1405 Madison St, Shelbyville, TN 37160",35.485660,-86.421005
142,Shelbyville,Middle Tennessee Education Center,"Bedford County, Tennessee",47003,"200 Dover St, Shelbyville, TN 37160",35.492680,-86.473213
143,Upper Cumberland,Bledsoe County Correctional Complex,"Bledsoe County, Tennessee",47007,"1045 Horsehead Rd, Pikeville, TN 37367",35.745304,-85.252338
144,Upper Cumberland,Main Campus,"Cumberland County, Tennessee",47035,"910 Miller Ave, Crossville, TN 38555",35.946995,-85.038815
145,Shelbyville,Adult Education Center,"Marshall County, Tennessee",47117,"218 W Commerce St, Lewisburg, TN 37091",35.449255,-86.789780

In [1272]:
test = data.merge(locs, on = ['Institution', 'Campus'], how = 'outer')

In [1274]:
###ALL GOOD
# bads = test.loc[test['Institution Address'].isna()]
# bads = bads[['Institution', 'Campus', 'Institution Address', 'Year']]
# bads = bads.drop_duplicates()
# bads.sort_values(by = 'Institution', ascending = True)
# # bads = bads.loc[bads['Institution'] == 'Memphis']
# # bads['Campus'].unique()
# # bads